//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWorkplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_Examinees
    {
        public System.Guid ExamineeID { get; set; }
        public System.Guid PersonID { get; set; }
        public Nullable<int> CodeNum { get; set; }
        public Nullable<System.Guid> SubjectID { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public int Score { get; set; }
        public int Items { get; set; }
    
        public virtual PW_Persons PW_Persons { get; set; }
        public virtual PW_Subjects PW_Subjects { get; set; }
    }
}
