//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWorkplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_Resources
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PW_Resources()
        {
            this.PW_TeamResources = new HashSet<PW_TeamResources>();
        }
    
        public System.Guid ResourceID { get; set; }
        public string ResourceName { get; set; }
        public string ResourcePath { get; set; }
        public string ResourceCategory { get; set; }
        public bool IsUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PW_TeamResources> PW_TeamResources { get; set; }
    }
}
