//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWorkplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_TeamResources
    {
        public int TeamResourceID { get; set; }
        public System.Guid TeamID { get; set; }
        public System.Guid ResourceID { get; set; }
    
        public virtual PW_Resources PW_Resources { get; set; }
        public virtual PW_Teams PW_Teams { get; set; }
    }
}
